### ISSUE TITLE
buttons on the main interface for new/delete

### ISSUE THREAD

**Issue by mortee** [k5md/Pocket-Editor-webextension#7]
When I open PE it's 99% of the time to quickly type or paste something for later use. And most of those texts get trashed very soon. Thus, the need to actually open the menu so that I can obtain a fresh editor, and also to get rid of the current one, is an unnecessary extra step for such oft-used functions. It would be better to have buttons for these in the header or footer.

**Comment by k5md** [comment]
Thanks, that's a reasonable request, I'll add these quick action buttons soon

**Comment by mortee** [comment]
A trash icon would be more standard for deleting the current file, other than that, it's nice and working!
